import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            // Lade NIC Config für den Browser
            window.nicConfig = {
              grid: {
                columns: 12,
                minRows: 10,
                maxRows: 0,
                gap: 8,
                rowHeight: 60,
                breakpoints: {
                  mobile: { maxWidth: 768, columns: 6, rowHeight: 50 },
                  tablet: { maxWidth: 1024, columns: 8, rowHeight: 55 },
                  desktop: { minWidth: 1025, columns: 12, rowHeight: 60 }
                }
              },
              defaultBlockSizes: {
                Text: { width: 6, height: 2 },
                ButtonBlock: { width: 3, height: 1 },
                ImageBlock: { width: 4, height: 3 },
                VideoBlock: { width: 6, height: 4 },
                ContainerBlock: { width: 12, height: 6 },
                TestBlock: { width: 4, height: 2 },
                DefaultHeader: { width: 12, height: 2 },
                NavigationHeader: { width: 12, height: 2 },
                DefaultFooter: { width: 12, height: 2 },
                SocialFooter: { width: 12, height: 2 },
                ContactFormBlock: { width: 6, height: 8 },
                NewsletterBlock: { width: 4, height: 3 },
                ColumnsBlock: { width: 12, height: 6 },
                GridBlock: { width: 12, height: 8 },
                AudioBlock: { width: 6, height: 2 },
                GalleryBlock: { width: 8, height: 6 }
              },
              visual: {
                showGridLines: true,
                showBlockOutlines: true,
                highlightDropZones: true,
                gridLineColor: 'rgba(99, 102, 241, 0.2)',
                dropZoneColor: 'rgba(34, 197, 94, 0.3)',
                selectedBlockColor: 'rgba(59, 130, 246, 0.5)'
              }
            };
          `
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
